-- Migration: Add archetype fields to users
-- Archetype is generated by LLM after user completes their first session

ALTER TABLE users ADD COLUMN archetype_name VARCHAR(100);
ALTER TABLE users ADD COLUMN archetype_description TEXT;
