"""
Domain Entities - Core business objects
"""
from pydantic import BaseModel
from typing import Literal, Optional, List
from datetime import datetime
from enum import Enum
import json

class Element(str, Enum):
    EARTH = "earth"
    FIRE = "fire"
    AIR = "air"
    WATER = "water"
    CHANGE = "change"

class SubElement(str, Enum):
    ONE = "1.0"
    TWO = "2.0"
    THREE = "3.0"
    TRANSFORM = "transform"

class SessionStatus(str, Enum):
    IN_PROGRESS = "in_progress"
    COMPLETED = "completed"
    ABANDONED = "abandoned"

class User(BaseModel):
    id: str
    clerk_id: str
    email: Optional[str] = None
    created_at: Optional[datetime] = None
    updated_at: Optional[datetime] = None
    # Archetype (generated by LLM after first completed session)
    archetype_name: Optional[str] = None  # e.g., "The Groundkeeper"
    archetype_description: Optional[str] = None  # 1 sentence description
    avatar_image_url: Optional[str] = None  # DALL-E generated avatar based on elements

class Session(BaseModel):
    id: str
    user_id: str
    puzzle_id: Optional[str] = None
    problem_description: Optional[str] = None
    thinker_description: Optional[str] = None  # Generated on first session completion
    started_at: datetime
    ended_at: Optional[datetime] = None
    status: SessionStatus = SessionStatus.IN_PROGRESS
    prompts_completed: int = 0
    created_at: Optional[datetime] = None
    # Cube visual properties (generated by LLM based on problem description)
    cube_primary_color: Optional[str] = None
    cube_secondary_color: Optional[str] = None
    cube_complexity: Optional[int] = None  # 1-5
    cube_label: Optional[str] = None  # 2-word label
    cube_image_url: Optional[str] = None  # DALL-E generated image URL
    # Unified understanding document (built/updated by LLM during session)
    understanding_document: Optional[str] = None

class Response(BaseModel):
    id: str
    session_id: str
    prompt_index: int
    element: Element
    sub_element: SubElement
    response_text: str
    word_count: int
    time_spent_seconds: int
    created_at: Optional[datetime] = None

class Hint(BaseModel):
    id: str
    session_id: str
    hint_text: str
    element_focus: Optional[Element] = None
    patterns_detected: Optional[dict] = None
    user_final_response: Optional[str] = None
    created_at: Optional[datetime] = None

class Puzzle(BaseModel):
    id: str
    title: str
    scenario: str
    constraints: List[str] = []
    example: str
    solution: str
    created_at: Optional[datetime] = None

class Component(BaseModel):
    id: str
    session_id: str
    puzzle_id: str
    user_id: str
    title: str
    key_insight: str
    input_context: str
    output_capability: str
    created_at: Optional[datetime] = None

class ElementMessage(BaseModel):
    id: str
    session_id: str
    prompt_index: int = 0  # Kept for backward compatibility, not used in new architecture
    role: str  # "user" or "assistant"
    message_text: str
    element_applied: Optional[str] = None  # Which element was invisibly applied (earth/fire/air/water/change)
    created_at: Optional[datetime] = None

class DeepUnderstanding(BaseModel):
    id: str
    session_id: str
    prompt_index: int = 0  # Kept for backward compatibility, not used in new architecture
    element: str  # Which element was invisibly applied
    insight_text: str
    created_at: Optional[datetime] = None

# The 12 prompts + Change (4 elements × 3 sub-elements + 1)
# MUYAIUM: AI-utilization wording. Original prompt names from the book retained.
PROMPTS = [
    # Earth (Deep Understanding)
    {
        "index": 0,
        "element": Element.EARTH,
        "sub_element": SubElement.ONE,
        "name": "Start with Simple",
        "prompt": "What are the fundamentals of this problem? What do you understand and what don't you? If there are gaps in your understanding, how would you use AI to fill them?",
    },
    {
        "index": 1,
        "element": Element.EARTH,
        "sub_element": SubElement.TWO,
        "name": "Spotlight Specific",
        "prompt": "Create a simpler, concrete version of this scenario. If you were to ask AI about just this simplified version, what would you ask?",
    },
    {
        "index": 2,
        "element": Element.EARTH,
        "sub_element": SubElement.THREE,
        "name": "Add the Adjective",
        "prompt": "Pick a word to describe your approach: iterative, exploratory, defensive, cautious, aggressive. How does that lens change how you'd work with AI on this problem?",
    },
    # Fire (Embrace Failure)
    {
        "index": 3,
        "element": Element.FIRE,
        "sub_element": SubElement.ONE,
        "name": "Fail Fast",
        "prompt": "Try something with AI — even if it's wrong. What would you ask or tell the AI right now as a rough first attempt?",
    },
    {
        "index": 4,
        "element": Element.FIRE,
        "sub_element": SubElement.TWO,
        "name": "Fail Again",
        "prompt": "What would go wrong with that approach? Where would the AI misunderstand you or give you something useless? What did you learn from that failure?",
    },
    {
        "index": 5,
        "element": Element.FIRE,
        "sub_element": SubElement.THREE,
        "name": "Fail Intentionally",
        "prompt": "What is the worst possible way to use AI on this problem? What would a completely wrong approach look like? What does imagining that failure teach you about the right approach?",
    },
    # Air (Create Questions)
    {
        "index": 6,
        "element": Element.AIR,
        "sub_element": SubElement.ONE,
        "name": "Be Your Own Socrates",
        "prompt": "Step back. What is the REAL question here? Are you even asking AI the right thing? Is there a bigger or different question you should be exploring?",
    },
    {
        "index": 7,
        "element": Element.AIR,
        "sub_element": SubElement.TWO,
        "name": "Ask Basic Questions",
        "prompt": "What fundamental concept about this problem or these AI tools do you not understand? What basic question would you ask AI that might unlock your understanding?",
    },
    {
        "index": 8,
        "element": Element.AIR,
        "sub_element": SubElement.THREE,
        "name": "Ask Another Question",
        "prompt": "What related problem might give you insight into this one? Is there a simpler or adjacent question you could explore with AI first?",
    },
    # Water (Flow of Ideas)
    {
        "index": 9,
        "element": Element.WATER,
        "sub_element": SubElement.ONE,
        "name": "Run Down All Paths",
        "prompt": "What are ALL the possible ways you could use AI to tackle this? List every approach you can think of — tools, prompts, strategies, workflows.",
    },
    {
        "index": 10,
        "element": Element.WATER,
        "sub_element": SubElement.TWO,
        "name": "Embrace Doubt",
        "prompt": "What are you uncertain about in your approach? Where might you be wrong? What would someone who disagrees with your approach say?",
    },
    {
        "index": 11,
        "element": Element.WATER,
        "sub_element": SubElement.THREE,
        "name": "Never Stop",
        "prompt": "Take your best approach and follow it to the end. What happens next? And after that? Where does this chain of thinking lead?",
    },
    # Change (Be Open to Change)
    {
        "index": 12,
        "element": Element.CHANGE,
        "sub_element": SubElement.TRANSFORM,
        "name": "Transform",
        "prompt": "How has thinking through this puzzle changed your understanding? What do you see differently now about how to use AI for this kind of problem?",
    },
]

def get_prompt(index: int) -> dict:
    """Get prompt by index (0-12)"""
    if 0 <= index < len(PROMPTS):
        return PROMPTS[index]
    return None


# ============ Course (Phase 2) ============
# A Course is the user's commitment to becoming more effective at X.
# It owns an intake chatbot conversation; once the intake produces a sharp
# "crisp statement" we save the structured fields and the course moves on
# to puzzle generation (phase 3).


class IntakeMessage(BaseModel):
    role: Literal["user", "assistant"]
    content: str
    created_at: Optional[datetime] = None


class Course(BaseModel):
    id: str
    user_id: str

    intake_status: Literal["draft", "in_progress", "complete", "abandoned"] = "in_progress"
    intake_messages: List[IntakeMessage] = []

    crisp_statement: Optional[str] = None
    # Short label used for course title/UI. Completes:
    # "I want to think more effectively in ___"
    course_label: Optional[str] = None
    domain: Optional[str] = None
    what: Optional[str] = None
    why: Optional[str] = None
    blocker: Optional[str] = None
    effective_looks_like: Optional[str] = None
    raw_quotes: Optional[List[str]] = None

    course_status: Literal[
        "awaiting_puzzles",
        "generating",
        "generation_failed",
        "ready",
        "active",
        "completed",
        "abandoned",
    ] = "awaiting_puzzles"

    # Generation metadata (phase 3)
    generation_error: Optional[str] = None
    generation_started_at: Optional[datetime] = None
    generation_completed_at: Optional[datetime] = None

    created_at: Optional[datetime] = None
    updated_at: Optional[datetime] = None


# ============ Course Puzzles (Phase 3) ============

class CoursePuzzle(BaseModel):
    id: str
    course_id: str
    position: int

    title: str
    puzzle_text: str
    answer: str  # internal-only; never exposed via API
    primary_element: Literal["earth", "fire", "air", "water", "synthesis"]
    why_this_trains_the_element: str
    domain_connection: str
    bridge_back: str

    status: Literal["pending", "in_progress", "completed", "skipped"] = "pending"
    completed_at: Optional[datetime] = None

    # Which stage the user is currently on (1=Think, 2=Redirect,
    # 3=Quintessence). Defaults to 1 for fresh puzzles. The canvas page
    # restores this on mount so leaving and returning preserves progress.
    current_stage: int = 1

    # Stage 3: synthesis paragraph (generated by AI on puzzle completion)
    synthesis: Optional[str] = None
    synthesis_generated_at: Optional[datetime] = None
    # Stage 3 sub-phase: 'reflect' or 'bridge'
    stage3_phase: Optional[Literal["reflect", "bridge"]] = None

    created_at: Optional[datetime] = None
    updated_at: Optional[datetime] = None


# ============ Canvas: Thoughts & Connections (Phase 4b) ============

class Thought(BaseModel):
    id: str
    course_puzzle_id: str
    user_id: str

    element: Optional[str] = None
    sub_element: Optional[str] = None
    content: str

    flow_order: int
    time_spent_seconds: Optional[int] = None

    pos_x: float = 0
    pos_y: float = 0

    # AI-generated nudge thoughts dropped on the canvas at the Stage 1 →
    # Stage 2 transition. Default False; set True only by the nudge
    # generation endpoint.
    is_nudge: bool = False

    # Stage 3 adds 'reflection' kind. 'thought' = Stage 1 user thought,
    # 'nudge' = Stage 2 AI nudge, 'reflection' = Stage 3 user reflection.
    kind: Literal["thought", "nudge", "reflection"] = "thought"

    created_at: Optional[datetime] = None
    updated_at: Optional[datetime] = None


class ThoughtConnection(BaseModel):
    id: str
    course_puzzle_id: str
    user_id: str

    from_thought_id: str
    to_thought_id: str

    created_at: Optional[datetime] = None
