"""Prompt template for Fire Starter symbolic editorial illustrations."""

FIRE_STARTER_IMAGE_PROMPT_TEMPLATE = """Create a square 1:1 abstract 3D editorial illustration. FIXED VISUAL STYLE — keep this consistent every time: Use a clean contemporary surreal 3D style, like a polished editorial illustration for psychology, education, puzzles, or ideas. The image should feel sculptural, symbolic, and slightly dreamlike. The composition should be built from simple geometric forms: arches, stairs, ladders, ramps, spheres, circles, portals, platforms, bowls, masks, clouds, trees, ribbons, and architectural fragments. Use playful impossible-architecture logic, where objects feel meaningful but not literal. Use a strict minimal color palette: matte pure white sculptural forms, deep navy / cobalt blue, vivid red, pale sky blue accents, soft light gray background. Avoid beige, tan, brown, orange, purple, green, noisy textures, realistic environments, or photographic clutter. Lighting should be soft studio lighting with gentle shadows, smooth matte surfaces, subtle ambient occlusion, and crisp clean edges. The image should feel premium, minimal, and designed. Background: Use a clean light gray or white background with large diagonal geometric color planes in red, navy, and pale blue. The background should feel like a modernist poster or abstract stage. Composition rules: Center the main symbolic object. Keep the image uncluttered. Use strong negative space. Make the object feel like a miniature surreal stage or monument. No text, no logos, no people, no realistic faces unless specifically requested. The image should communicate the idea through metaphor, not literal explanation. SUBJECT / CONCEPT TO SYMBOLIZE: {lesson_description} INTERPRETATION INSTRUCTIONS: Turn the concept into a symbolic surreal scene using the fixed visual language above. Choose 3-5 visual metaphors that represent the concept. Make the image feel clever, mysterious, and intellectually playful, like a puzzle object. The final image should look like it belongs in the same visual series as the reference images: clean 3D, geometric, red-white-blue palette, surreal educational symbolism, premium editorial design."""


def build_fire_starter_image_prompt(lesson_description: str) -> str:
    """Substitute the lesson description into the fixed-style image prompt."""
    desc = (lesson_description or "").strip() or "A pattern of thinking earned through puzzle-solving."
    return FIRE_STARTER_IMAGE_PROMPT_TEMPLATE.format(lesson_description=desc)
